### ISSUE TITLE
Implement route repository API 

### ISSUE THREAD

**Issue by defiancecp** [defiancecp/GTBikeVRouteDB#8]
Currently interpreting from a readme in the repository - move to more sustainable approach using API.

**Comment by murech** [comment]
Hi @defiancecp. FYI - I created an API for html metadata. You find the API specification here: https://github.com/gtbikev/docs/tree/master/api. The html metadata API is accessible here: https://github.com/gtbikev/courses/blob/master/api/html-api.html

I moved the api to automate course repository changes. This gives you more flexibility to change to another API and prevents a breaking change once the html metadata is not available anymore in the current README. Moreover, I think it's a better design to separate documentation from course metadata.

Can you please change the RouteDB to point to the new API and let me know?

**Comment by defiancecp** [comment]
Moved to the new file location successfully.  Holding this open to follow any structure changes.

**Comment by oldnapalm** [comment]
The map preview is not working for various routes (even those with the globe icon).

Now all fit files are available at https://github.com/gtbikev/courses/tree/master/fit

**Comment by murech** [comment]
Hi @defiancecp 

The concept of course id was introduced in version 0.4.1.x with the new course selector. The idea behind this is that a course can be renamed and to simplify the update process. Unfortuanely this caused a braking change for route db because the name of the course files changed as well.

I updated the api metadata for route db. But the courses have now the id in the name as well. For example: 5-the-tourist. I suggest to introduce a new field in the api metadata called **DisplayName** in order to display the course name instead the file name.

Please let me know if I should add the field **DisplayName** to the API.

**Comment by defiancecp** [comment]
As discussed in chat -- Yes please on the displayname thing :)  I've got stubs in the db and stored procs are updated to handle it, just need to update the import once the change is in place on your end -- then once processing is tested OK in the back end, I'll switch what's shown on the site.

**Comment by murech** [comment]
Field DisplayName is implemented. You can implement the changes on your end.

**Comment by defiancecp** [comment]
I've incorporated displayname, and implemented fit file capture as part of cron job-- I think we're good :)
